# SPDX-License-Identifier: GPL-2.0-only
# Suppress modalias autoload. The guarded late service uses explicit modprobe.
blacklist apple_ibridge
blacklist apple_touchbar

options apple_ibridge skip_acpi_power=1
options apple_touchbar fnmode=2 idle_timeout=-1 dim_timeout=-1
