# SPDX-License-Identifier: GPL-2.0-only
PACKAGE_NAME="apple-t1-touchbar"
PACKAGE_VERSION="0.1.r2.ga33c7eb"
BUILT_MODULE_NAME[0]="apple-ibridge"
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILT_MODULE_NAME[1]="apple-touchbar"
DEST_MODULE_LOCATION[1]="/updates/dkms"
MAKE[0]="make KVERSION=${kernelver}"
AUTOINSTALL="yes"
